version: '3'
services:
  redis-cluster:
    build:
      context: ./redis_docker
      dockerfile: Dockerfile_redis
    hostname: redis_cluster
    ports:
      - "30001-30006:30001-30006/tcp"
    networks:
      - my-custom-network

  poc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-cluster
    ports:
      - "8080:8080"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge

