FROM ubuntu:20.04

ENV REDIS_VERSION=7.0.12

RUN apt-get update && \
    apt-get install -y wget build-essential && \
    apt-get install -y vim && \
    rm -rf /var/lib/apt/lists/*

RUN wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz && \
    tar xzf redis-${REDIS_VERSION}.tar.gz && \
    rm redis-${REDIS_VERSION}.tar.gz

WORKDIR /redis-${REDIS_VERSION}

RUN make && \
    make install && \
    chmod 777 utils

EXPOSE 30001 30002 30003 30004 30005 30006

RUN echo "#!/bin/bash\ncd utils/create-cluster\nsed -i 's/PROTECTED_MODE=yes/PROTECTED_MODE=no/g' create-cluster\ncontainer_ip=\$(hostname -i)\nsed -i \"s/CLUSTER_HOST=127.0.0.1/CLUSTER_HOST=\${container_ip}/g\" create-cluster\n./create-cluster start\necho 'yes' | ./create-cluster create\nbash" > setup-cluster.sh

RUN chmod +x setup-cluster.sh

CMD ["./setup-cluster.sh"]
