FROM ubuntu:20.04

ENV REDIS_VERSION=7.0.12

RUN apt-get update && \
    apt-get install -y wget build-essential && \
    apt-get install -y vim && \
    rm -rf /var/lib/apt/lists/*

RUN wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz && \
    tar xzf redis-${REDIS_VERSION}.tar.gz && \
    rm redis-${REDIS_VERSION}.tar.gz

WORKDIR /redis-${REDIS_VERSION}

RUN make && \
    make install && \
    chmod 777 utils

EXPOSE 30001 30002 30003 30004 30005 30006

RUN echo "#!/bin/bash" > setup-cluster.sh && \
    echo "cd utils/create-cluster" >> setup-cluster.sh && \
    echo "sed -i 's/PROTECTED_MODE=yes/PROTECTED_MODE=no/g' create-cluster" >> setup-cluster.sh && \
    echo "container_ip=\$(hostname -i)" >> setup-cluster.sh && \
    echo "sed -i \"s/CLUSTER_HOST=127.0.0.1/CLUSTER_HOST=\${container_ip}/g\" create-cluster" >> setup-cluster.sh && \
    echo "./create-cluster start" >> setup-cluster.sh && \
    echo "echo 'yes' | ./create-cluster create" >> setup-cluster.sh && \
    #echo "\${container_ip} redis-cluster >> /etc/hosts" >> setup-cluster.sh && \
    echo "bash" >> setup-cluster.sh

RUN chmod +x setup-cluster.sh

CMD ["./setup-cluster.sh"]
